## EXERCISE 1: What to do at the airport?

You are travelling and have some time to kill at the aiport. There are three things you could spend your time doing:
  
1) You could have a coffee.

This has a probability of $0.8$ of giving you time to relax with a tasty beverage, and a utility of $10$.
It also has a probability of $0.2$ of providing you with a nasty cup from over-roasted beans that annoys you,
and outcome with a utility of $-5$.

2) You could shop for clothes.

This has a probability of $0.1$ that you will find a great outfit at a good price, utility $20$. However, it
has a probability of $0.9$ that you end up wasting money on over-priced junk, utility $-10$.

3) You could have a bite to eat.

This has a probability of $0.8$ that you find something rather mediocre that prevents you from being too hungry
during your flight, utility $2$, and a probability of $0.2$ that you find something filling and tasty, utility $5$.

> __QUESTION 1(a):__ What should you do if you take the principle of maximum expected utility to be your decision criterion?

> __QUESTION 1(b):__ What should you do if you take the principle of maximax decision criterion to be your decision criterion?

> __QUESTION 1(c):__ What should you do if you take the principle of maximin decision criterion to be your decision criterion?
    

> __QUESTION 1(a):__ What should you do if you take the principle of maximum expected utility to be your decision criterion?

Coffee

In [4]:
import numpy as np

coffe_outputs = np.array(["tasty", "nasty"])
U_coffee_outcomes = np.array([10, -5])
P_coffee_outcomes_coffee = np.array([0.8, 0.2])

#expected utility
eu_coffee_outcomes = U_coffee_outcomes * P_coffee_outcomes_coffee
eu_coffee = np.sum(eu_coffee_outcomes)
print(eu_coffee)

7.0


Shopping

In [7]:
shopping_outputs = np.array(["good_fit", "bad_fit"])
U_shopping_outcomes = np.array([20, -10])
P_shopping_outcomes_shopping = np.array([0.1, 0.9])

#expected utility
eu_shopping_outcomes = U_shopping_outcomes * P_shopping_outcomes_shopping
eu_shopping = np.sum(eu_shopping_outcomes)
print(eu_shopping)

-7.0


Eat

In [8]:
eat_outputs = np.array(["good_food", "bad_fit"])
U_eat_outcomes = np.array([5, 2])
P_eat_outcomes_eat = np.array([0.2, 0.8])

#expected utility
eu_eat_outcomes = U_eat_outcomes * P_eat_outcomes_eat
eu_eat = np.sum(eu_eat_outcomes)
print(eu_eat)

2.6


Following the $MEU$ principle, the best chioce is to go for a coffee.

> __QUESTION 1(b):__ What should you do if you take the principle of maximax decision criterion to be your decision criterion?

The best choice is to go shopping because in the maximax principle you pick the maximum utility of each possible action's outcomes anch pick that action

> __QUESTION 1(c):__ What should you do if you take the principle of maximin decision criterion to be your decision criterion?

The best choice following the maxmin criterion is to eat something because we pick the worst outcome of all actions and choose the maximum between them.

## EXERCISE 2: Solving a MDP with MDP toolbox

We have four states and four actions.

The actions are: 0 is Right, 1 is Left, 2 is Up and 3 is Down.

The states are 0, 1, 2, 3, and they are arranged like this:
    
$$
\begin{array}{cc}
2 & 3\\
0 & 1\\
\end{array}
$$

The motion model provides:
*   0.8 probability of moving in the direction of the action,
*   0.1 probability of moving in each of the directions perpendicular to that of the action.

So that 2 is Up from 0 and 1 is Right of 0, and so on. The cost of any action (in any state) is -0.04.

In case of "infeasible" movements, the agent remains in the current state with probability 0.8+0.1. Consider the perpendicular directions in any case.

The reward for state 3 is 1, and the reward for state 1 is -1, and the agent does not leave those states.

Set discount factor equal to 0.99.

Initial state is 0

> __QUESTION 2(a):__ What is the policy based on the Value iteration algorithm?

> __QUESTION 2(b):__ What is the policy based on the Policy iteration algorithm?

> __QUESTION 2(c):__ What is the policy based on the Q-Learning algorithm?

> __QUESTION 2(d):__ Look at the **setVerbose**() function and the time attribute of the MDP objects in MDPToolbox and use them to compare the number of iterations (hint: see the iter attribute) and the CPU time used to come up with a solution (hint: see the time attribute) in the Value iteration algorithm and Policy iteration algorithm resolutions.


In [15]:
!pip install pymdptoolbox
import mdptoolbox
import numpy as np

Prepare the matrices

In [36]:
#probability array
#                0   1   2   3         states reached

P = np.array([[[0, 0.8, 0.2, 0],  #current state: 0
                [0, 1, 0, 0],  #s1
                [0.1, 0, 0.1, 0.8],  #s2            #action: Right (0)
                [0, 0, 0, 1]], #s3 etc ...
               [[0.9, 0, 0.1, 0],
                [0, 1, 0, 0],
                [0.1, 0, 0.9, 0],      #Left (1)
                [0, 0, 0, 1]],
               [[0.1, 0.1, 0.8, 0],
                [0, 1, 0, 0],
                [0, 0, 0.9, 0.1],      #Up (2)
                [0, 0, 0, 1]],
               [[0.9, 0.1, 0, 0],
                [0, 1, 0, 0],
                [0.8, 0, 0, 0.2],      #Down (3)
                [0, 0, 0, 1]]])


#  actions      R    L      U      D

R = np.array([[-1, -0.04, -0.04, -0.04],     #s0
              [-1, -1, -1, -1],        #s1
              [1, -0.04, -0.04, -0.04],      #s2
              [1, 1, 1, 1]])            #s3



print('Probabilities\n\n', P, '\n\n\nRewards\n\n', R)

Probabilities

 [[[0.  0.8 0.2 0. ]
  [0.  1.  0.  0. ]
  [0.1 0.  0.1 0.8]
  [0.  0.  0.  1. ]]

 [[0.9 0.  0.1 0. ]
  [0.  1.  0.  0. ]
  [0.1 0.  0.9 0. ]
  [0.  0.  0.  1. ]]

 [[0.1 0.1 0.8 0. ]
  [0.  1.  0.  0. ]
  [0.  0.  0.9 0.1]
  [0.  0.  0.  1. ]]

 [[0.9 0.1 0.  0. ]
  [0.  1.  0.  0. ]
  [0.8 0.  0.  0.2]
  [0.  0.  0.  1. ]]] 


Rewards

 [[-1.   -0.04 -0.04 -0.04]
 [-1.   -1.   -1.   -1.  ]
 [ 1.   -0.04 -0.04 -0.04]
 [ 1.    1.    1.    1.  ]]


In [37]:
mdptoolbox.util.check(P, R)

> __QUESTION 2(a):__ What is the policy based on the Value iteration algorithm?


In [38]:
vi = mdptoolbox.mdp.ValueIteration(P, R, 0.99)    #gamma = 0.99
vi.run()

print('Values:\n', vi.V)
print('Policy:\n', vi.policy)

Values:
 (89.39593961732311, -99.9949804281095, 98.83037993946596, 99.9949804281095)
Policy:
 (1, 0, 0, 0)


So, the best actions are: left, right, right, right

> __QUESTION 2(b):__ What is the policy based on the Policy iteration algorithm?


In [39]:
pi = mdptoolbox.mdp.PolicyIteration(P, R, 0.99)
pi.run()
print('Values:\n', pi.V)
print('Policy:\n', pi.policy)

Values:
 (89.4009591892136, -99.99999999999991, 98.83539951135636, 99.99999999999991)
Policy:
 (1, 0, 0, 0)


> __QUESTION 2(c):__ What is the policy based on the Q-Learning algorithm?


In [43]:
ql = mdptoolbox.mdp.QLearning(P, R, 0.9)
ql.run()
print('Values:\n', ql.V)
print('Policy:\n', ql.policy)

Values:
 (0.79201207247038, -7.528637632723187, 5.014961486183891, 9.999932089838087)
Policy:
 (1, 0, 0, 0)
